"""create study tasks table

Revision ID: 514d0fc3e13b
Revises: 200daeae0f4b
Create Date: 2026-09-17 20:57:36.151106

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '514d0fc3e13b'
down_revision: str | Sequence[str] | None = '200daeae0f4b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_tasks_scheduled_date'), 'study_tasks', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_study_tasks_study_plan_id'), 'study_tasks', ['study_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_tasks_study_plan_id'), table_name='study_tasks')
    op.drop_index(op.f('ix_study_tasks_scheduled_date'), table_name='study_tasks')
    op.drop_table('study_tasks')
    # ### end Alembic commands ###
